Upload log

diff --git a/.github/workflows/workers.yaml b/.github/workflows/workers.yaml
--- a/.github/workflows/workers.yaml
+++ b/.github/workflows/workers.yaml
@@ -56,7 +56,20 @@ jobs:
           secrets: |-
             cloudflare_token:kotori316-mods-resources/cloudflare_token
       - name: Deploy
-        run: npm run deploy >/dev/null && echo "Published successfully" || (echo "Failed to publish"; false)
+        id: action
+        run: |
+          log_name="$(date "+%Y%m%d-%H%M%S")-npm-deploy.log"
+          echo "${{ github.actor }}" >> "/tmp/${log_name}"
+          echo "name=${log_name}" >> $GITHUB_OUTPUT
+          echo "repo=$(basename "${{github.repository}}")" >> $GITHUB_OUTPUT
+          npm run deploy >>"/tmp/${log_name}" 2>&1 && echo "Published successfully" || (echo "Failed to publish"; false)
         working-directory: 'workers'
         env:
           CLOUDFLARE_API_TOKEN: ${{steps.get-secrets.outputs.cloudflare_token}}
+      - name: Upload log
+        if: ${{ !cancelled() }}
+        uses: google-github-actions/upload-cloud-storage@v2
+        with:
+          path: /tmp/${{steps.action.outputs.name}}
+          destination: kotori316-logs/${{steps.action.outputs.repo}}
+          process_gcloudignore: false
